# Machine Learning implementation Test


### 1. implement Decision Tree Classifier by applying HyperParameter Tuning also their metrics should be there.


In [44]:
import sklearn
import numpy as np

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

from sklearn.datasets import load_iris

In [45]:
irisds=load_iris()

In [46]:
irisds

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [47]:
df=pd.DataFrame(irisds.data,columns=irisds.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [48]:
df['target']=pd.DataFrame(irisds.target)

In [49]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [50]:
df.to_csv('myiris.csv')        #create our own csv

In [51]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [52]:
x=df.iloc[:,0:-1]

x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [53]:
y=df.iloc[:,-1]

y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [54]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20,random_state=45)

In [55]:
x_train.shape

(120, 4)

In [56]:
x_test.shape

(30, 4)

In [57]:
y_train.shape

(120,)

In [58]:
y_test.shape

(30,)

In [59]:
dtc=DecisionTreeClassifier(criterion='gini')  # #we can change the criterio untill the accuracy score is 1 and either entropy or gini
    

In [60]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [61]:
preddtc=dtc.predict(x_test)
preddtc

array([0, 0, 2, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 1, 0, 2, 2, 0, 1, 1, 1,
       2, 1, 0, 2, 1, 1, 0, 1])

In [62]:
accuracy_score(y_test,preddtc)

0.9666666666666667

In [63]:
print(confusion_matrix(y_test,preddtc))

[[11  0  0]
 [ 0  7  0]
 [ 0  1 11]]


In [64]:
print(classification_report(y_test,preddtc))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.88      1.00      0.93         7
           2       1.00      0.92      0.96        12

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



In [65]:
# Define hyperparameters to tune
parameters = {
    'max_depth': [3, 5, 7, 10],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

In [70]:
# Use Grid Search Cross Validation to find the best parameters
grid_search = GridSearchCV(dtc, parameters, cv=5, scoring='accuracy')
grid_search.fit((x_train, y_train)


In [72]:
# Get the best parameters
#best_params = grid_search.best_params_


In [56]:
# Initialize Decision Tree Classifier with best parameters
best_dt_classifier = DecisionTreeClassifier(**best_params)

In [57]:
# Train the model with best parameters
best_dt_classifier.fit(X_train, y_train)


DecisionTreeClassifier(max_depth=5, min_samples_leaf=2, min_samples_split=10)

In [58]:
# Predictions on the test set
y_pred = best_dt_classifier.predict(X_test)

In [59]:
y_pred

array([1, 0, 0, 1, 2, 2, 2, 0, 1, 1, 1, 2, 0, 2, 0, 1, 1, 1, 2, 1, 2, 1,
       2, 1, 0, 0, 2, 2, 2, 2])

In [60]:
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Best parameters:", best_params)
print("Accuracy:", accuracy)

Best parameters: {'max_depth': 5, 'min_samples_leaf': 2, 'min_samples_split': 10}
Accuracy: 0.26666666666666666


### 2. Implement Naive's Bayes Classifier by Applying HyperParameter Tuning 


In [61]:
from sklearn.naive_bayes import GaussianNB

In [62]:

# Define the Naive Bayes Classifier
nb_classifier = GaussianNB()


In [63]:
# Define hyperparameters to tune (Note: Naive Bayes doesn't have many hyperparameters to tune)
parameters = {
    'var_smoothing': np.logspace(0,-9, num=100)
}

In [64]:
# Use Grid Search Cross Validation to find the best parameters
grid_search = GridSearchCV(nb_classifier, parameters, cv=5)
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=GaussianNB(),
             param_grid={'var_smoothing': array([1.00000000e+00, 8.11130831e-01, 6.57933225e-01, 5.33669923e-01,
       4.32876128e-01, 3.51119173e-01, 2.84803587e-01, 2.31012970e-01,
       1.87381742e-01, 1.51991108e-01, 1.23284674e-01, 1.00000000e-01,
       8.11130831e-02, 6.57933225e-02, 5.33669923e-02, 4.32876128e-02,
       3.51119173e-02, 2.84803587e-02, 2.31...
       1.23284674e-07, 1.00000000e-07, 8.11130831e-08, 6.57933225e-08,
       5.33669923e-08, 4.32876128e-08, 3.51119173e-08, 2.84803587e-08,
       2.31012970e-08, 1.87381742e-08, 1.51991108e-08, 1.23284674e-08,
       1.00000000e-08, 8.11130831e-09, 6.57933225e-09, 5.33669923e-09,
       4.32876128e-09, 3.51119173e-09, 2.84803587e-09, 2.31012970e-09,
       1.87381742e-09, 1.51991108e-09, 1.23284674e-09, 1.00000000e-09])})

In [65]:
# Get the best parameters
best_params = grid_search.best_params_

In [66]:
# Initialize Naive Bayes Classifier with best parameters
best_nb_classifier = GaussianNB(var_smoothing=best_params['var_smoothing'])

In [67]:
# Train the model with best parameters
best_nb_classifier.fit(X_train, y_train)


GaussianNB(var_smoothing=0.01519911082952933)

In [68]:
# Predictions on the test set
y_pred = best_nb_classifier.predict(X_test)

In [69]:
# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Best parameters:", best_params)
print("Accuracy:", accuracy)

Best parameters: {'var_smoothing': 0.01519911082952933}
Accuracy: 0.23333333333333334


In [70]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.20      0.09      0.13        11
           1       0.18      0.43      0.25         7
           2       0.38      0.25      0.30        12

    accuracy                           0.23        30
   macro avg       0.25      0.26      0.23        30
weighted avg       0.26      0.23      0.22        30



### 3. Implement Support Vector Machine by applying HyperParameter Tuning 



In [71]:
from sklearn.svm import SVC

In [72]:
sv=SVC(kernel='rbf')       #kernel will improve the classifier and we take it either rbf or poly or linear

sv.fit(x_train,y_train)
svpr=sv.predict(x_test)

svpr

array([0, 0, 2, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 1, 0, 2, 2, 0, 1, 1, 1,
       2, 1, 0, 2, 1, 1, 0, 1])

In [73]:
accuracy_score(y_test,svpr)

0.9666666666666667

In [74]:
confusion_matrix(y_test,svpr)

array([[11,  0,  0],
       [ 0,  7,  0],
       [ 0,  1, 11]], dtype=int64)

In [75]:
sv=SVC(kernel='poly')       #kernel will improve the classifier and we take it either rbf or poly or linear

sv.fit(x_train,y_train)
svpr=sv.predict(x_test)

svpr

array([0, 0, 1, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 1, 0, 2, 2, 0, 1, 1, 1,
       2, 1, 0, 2, 1, 1, 0, 1])

In [76]:
accuracy_score(y_test,svpr)

0.9333333333333333

In [77]:
sv=SVC(kernel='linear')       #kernel linear is better in compare to other becouse in linear ony accuracy score is one

sv.fit(x_train,y_train)
svpr=sv.predict(x_test)

svpr

array([0, 0, 2, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 1, 1, 1,
       2, 1, 0, 2, 1, 1, 0, 1])

In [78]:
accuracy_score(y_test,svpr)

1.0

In [79]:
confusion_matrix(y_test,svpr)

array([[11,  0,  0],
       [ 0,  7,  0],
       [ 0,  0, 12]], dtype=int64)

In [80]:
# Define the Support Vector Machine (SVM) Classifier
svm_classifier = SVC()

In [74]:
# defining parameter range 
param_grid = {'C': [0.1, 1, 10, 100, 1000],'gamma': [1, 0.1, 0.01, 0.001, 0.0001],'kernel': ['rbf']}  
  
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3) 
  
fitting the model for grid search 
grid.fit(X_train, y_train) 

### 4. Explain various types of  Kernels with respect to the formula 


Kernels in Support Vector Machines (SVMs), supervised learning algorithms used for classification and regression tasks. Kernels are mathematical functions that take as input two vectors and output a scalar, representing the similarity or distance between the vectors. They allow SVMs to operate in a higher-dimensional space without explicitly computing the coordinates of the data in that space, thus enabling efficient classification in complex, non-linear decision boundaries. Here are the various types of kernels commonly used in SVMs:

### Linear Kernel:
The linear kernel is the simplest kernel and is used when the data is linearly separable. Its formula is:

K(x,x')=x.x'(x,x'->I/P FEATURES)

### Polynomial Kernel:
The polynomial kernel is used to handle non-linear classification problems. It computes the similarity between two vectors by projecting them into a higher-dimensional space using polynomial functions. Its formula is:

K(X,X')=(X,X'+C)^D

C-CONSTANCE

D-DEGREE OF POLYNOMIAL

### Radial Basis Function (RBF) Kernel:
The RBF kernel, also known as the Gaussian kernel, is one of the most commonly used kernels in SVMs. It measures the similarity between two vectors based on the Gaussian distribution of their distances. Its formula is:

K(X,X')=EXP(-||X-X'||^2/2 SIGMA^2)

X,X'->INPUT VECTORS

||X-X'||^2 = SQUARED EUCLIDEAN DISTANCE X,X'

SIGMA-> SPREADNESS OF KERNEL BANDWIDTH

### Sigmoid Kernel:
The sigmoid kernel maps the input vectors into a higher-dimensional space using a hyperbolic tangent function. It can be useful for non-linear classification problems, but it is less commonly used compared to the polynomial and RBF kernels. Its formula is:

K(x,y)=tanh(αxT y+c)

Where
α and c are parameters.